#!/usr/bin/env bs

# Name      : bfg
# Author    : Jore
# Purpose   : Output brainfuck code that prints the input

m +10
o 1
l:
	m -1
:l
r 1
m +7
l:
	l 1
	m +14
	r 1
	m -1
:l
l 1
o 1
m +3
r 1
m +4
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
o 1
r 2
m +2
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
m -1
o 1
l 1
m -15
o 1
m +5
o 1
m +3
o 1
m -13
o 1
r 1
m +1
o 1
r 1
m +5
l:
	l 1
	m +7
	r 1
	m -1
:l
o 1
r 1
m +5
l:
	l 1
	m +10
	r 1
	m -1
:l
l 1
l:
	l 1
	o 1
	r 1
	m -1
:l
r 1
m +2
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
o 1
l:
	m -1
:l
l 1
l:
	m -1
:l
l 1
l:
	m -1
:l
r 1
m +4
l:
	l 1
	m +8
	r 1
	m -1
:l
m +4
l:
	l 1
	o 4
	r 1
	m -1
:l
m +4
l:
	l 1
	m +8
	r 1
	m -1
:l
l 1
m +2
o 1
r 1
m +4
l:
	l 1
	m +4
	r 1
	m -1
:l
l 1
o 1
r 1
m +4
l:
	l 1
	m -4
	r 1
	m -1
:l
l 1
m -1
o 1
r 1
m +2
l:
	l 1
	m +4
	r 1
	m -1
:l
l 1
o 1
m +5
o 1
r 1
m +2
l:
	l 1
	m -4
	r 1
	m -1
:l
l 1
o 1
r 1
m +4
l:
	l 1
	m -7
	r 1
	m -1
:l
l 1
o 2
m +5
r 1
m +4
l:
	l 1
	m +7
	r 1
	m -1
:l
l 1
o 1
r 2
m +4
l:
	l 1
	m +8
	r 1
	m -1
:l
l 1
o 1
l 1
m -4
o 1
m -2
o 1
r 1
m -1
r 1
m +2
l:
	l 1
	m -11
	r 1
	m -1
:l
l 1
l:
	l 1
	m +1
	r 1
	m -1
:l
l 1
o 1
r 1
m +3
l:
	l 1
	m -3
	r 1
	m -1
:l
l 1
o 1
m +1
r 1
m +2
l:
	l 1
	m +6
	r 1
	m -1
:l
l 1
o 1
m -1
r 1
m +4
l:
	l 1
	m -4
	r 1
	m -1
:l
l 1
o 1
m +1
r 1
m +3
l:
	l 1
	m +6
	r 1
	m -1
:l
l 1
o 1
m -5
o 1
m +3
o 1
r 2
m +2
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
o 1
l:
	r 1
	m +3
	r 1
	m +5
	l 2
	m -1
:l
r 1
m +5
r 1
l:
	l 1
	o 1
	r 1
	m -1
:l
m +5
l:
	l 1
	m -5
	r 1
	m -1
:l
l 1
o 2
l 2
m +2
o 1
r 1
m +3
l:
	l 1
	m +7
	r 1
	m -1
:l
l 1
o 1
m +7
o 1
r 1
m +6
l:
	l 1
	m -9
	r 1
	m -1
:l
l 1
o 1
r 2
l:
	l 1
	m +3
	r 1
	m -1
:l
l 1
m +2
o 1
r 1
m +3
l:
	l 2
	m +9
	r 2
	m -1
:l
l 2
o 1
r 1
l:
	r 1
	m +1
	r 1
	m +1
	l 2
	m -1
:l
r 2
l:
	l 2
	m +1
	r 2
	m -1
:l
l 1
m -2
l:
	l 2
	m +1
	r 2
	m -1
:l
l 2
o 1
r 2
m +2
l:
	l 2
	m -7
	r 2
	m -1
:l
l 2
o 1
r 1
o 1
l 1
m -5
o 1
r 1
l:
	r 1
	m +1
	r 1
	m +1
	l 2
	m -1
:l
r 2
l:
	l 2
	m +1
	r 2
	m -1
:l
l 1
m +1
o 1
l 2
o 1
r 1
o 1
r 1
l:
	m -1
:l
m +4
l:
	l 2
	m +5
	r 2
	m -1
:l
l 2
o 1
m -5
o 1
r 1
o 1
r 1
m +2
l:
	l 2
	m -5
	r 2
	m -1
:l
l 2
o 1
r 2
m +3
l:
	l 2
	m +3
	r 2
	m -1
:l
l 2
o 1
r 2
m +2
l:
	l 2
	m -5
	r 2
	m -1
:l
l 2
o 1
r 1
o 1
l 1
m +5
o 1
m +5
o 1
m +2
o 1
m +5
o 1
m -1
o 1
r 2
m +2
l:
	l 1
	m +7
	r 1
	m -1
:l
l 1
o 1
r 2
m +2
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
o 2
l:
	l 1
	m +2
	r 1
	m -1
:l
l 1
m +3
o 1
l 1
m -6
o 1
m +6
o 1
r 2
m +3
l:
	l 2
	m -5
	r 2
	m -1
:l
l 2
o 1
m +3
r 2
m +2
l:
	l 2
	m +5
	r 2
	m -1
:l
l 2
o 1
r 1
m -5
r 1
m +4
l:
	l 1
	m -8
	r 1
	m -1
:l
l 1
o 1
r 1
m +5
l:
	l 2
	m -6
	r 2
	m -1
:l
l 2
o 1
m +1
r 2
m +4
l:
	l 2
	m +4
	r 2
	m -1
:l
l 2
o 1
m +1
r 2
m +3
l:
	l 2
	m +6
	r 2
	m -1
:l
l 2
o 1
m -4
o 1
r 1
m -2
r 1
m +4
l:
	l 1
	m -5
	r 1
	m -1
:l
l 1
o 2
r 1
m +6
l:
	l 2
	m -9
	r 2
	m -1
:l
l 2
o 1
r 1
m +2
r 1
m +4
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
o 1
l:
	m -1
:l
l 1
l:
	m -1
:l
r 2
i 1
l:
	r 1
	m +1
	r 1
	m +1
	l 2
	m -1
:l
r 2
l:
	l 2
	m +1
	r 2
	m -1
:l
m +3
r 1
m +5
l:
	l 1
	m +6
	r 1
	m -1
:l
l 1
l:
	l 1
	m -1
	r 1
	m -1
:l
l 1
l:

	l:
		m -1
	:l
	r 1
	m +1
	l:
		m -1
		l 1
		i 1
		l:
			r 1
			m +1
			r 1
			m +1
			l 2
			m -1
		:l
		r 2
		l:
			l 2
			m +1
			r 2
			m -1
		:l
		m +3
		r 1
		m +5
		l:
			l 1
			m +6
			r 1
			m -1
		:l
		l 1
		l:
			l 1
			m -1
			r 1
			m -1
		:l
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m +1
			l 1
		:l
		r 1
	:l

:l
r 1
m +2
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
o 1
r 1
m +9
l:
	l 1
	m +9
	r 1
	m -1
:l
l 1
m -2
o 1
r 1
m +2
l:
	l 1
	m +11
	r 1
	m -1
:l
l 1
o 1
m +6
o 1
m -3
o 1
r 3
m +4
l:
	l 1
	m +8
	r 1
	m -1
:l
l 1
o 1
l 2
m +2
o 1
r 1
m +3
l:
	l 1
	m -5
	r 1
	m -1
:l
l 1
o 1
m +1
r 1
m +3
l:
	l 1
	m +6
	r 1
	m -1
:l
l 1
o 1
m -4
o 1
r 2
o 1
l 2
m -1
r 1
m +2
l:
	l 1
	m -5
	r 1
	m -1
:l
l 1
o 1
m +5
o 1
r 2
o 1
l 1
m +2
l:
	l 1
	m -6
	r 1
	m -1
:l
l 1
o 1
r 1
m +4
l:
	l 1
	m +4
	r 1
	m -1
:l
l 1
o 1
m -1
r 1
m +4
l:
	l 1
	m -4
	r 1
	m -1
:l
l 1
o 1
r 1
m +2
l:
	l 1
	m +4
	r 1
	m -1
:l
l 1
o 1
m +5
o 1
r 1
m +2
l:
	l 1
	m -4
	r 1
	m -1
:l
l 1
o 1
r 1
m +3
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
o 1
r 1
m +3
l:
	l 1
	m -6
	r 1
	m -1
:l
l 1
o 1
r 1
m +2
l:
	l 1
	m +4
	r 1
	m -1
:l
l 1
o 1
r 2
o 1
l 2
m -2
o 1
r 1
m +2
l:
	l 1
	m +5
	r 1
	m -1
:l
l 1
o 1
r 1
m +7
l:
	l 1
	m -8
	r 1
	m -1
:l
l 1
o 1
r 2
m -2
r 1
m +4
l:
	l 1
	m -5
	r 1
	m -1
:l
l 1
o 2
l 4
l:
	m -1
:l
l 1
l:
	l 1
:l
r 1
l:
	l 1
	l:
		m -1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	m +3
	l 1
	m +5
	l:
		r 1
		m +8
		l 1
		m -1
	:l
	r 2
	l:
		l 1
		o 1
		r 1
		m -1
	:l
	l 1
	m +3
	o 1
	r 1
	m +4
	l:
		l 1
		m +4
		r 1
		m -1
	:l
	l 1
	o 1
	r 2
:l
