#!/usr/bin/env bs

# Name      : tictactoe
# Author    : unknown
# Purpose   : Tic Tac Toe game

l 1
m +5; m +5
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +4
o 1
m +5; m +5; m +5; m +5; m +1
o 1
m -5; m -1
o 1
m -5; m -5; m -5
o 1
m +5; m +5; m +3
o 1
m +2
o 1
m -5; m -5; m -5
o 1
m +5; m +5; m +5; m +5; m +5
m +2
o 1
m -5; m -5
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -1
o 2
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5
o 1
m +5; m +5; m +5; m +5; m +5
m +3
o 1
m -5; m -2
o 1
m -4
o 1
m +5; m +5; m +5; m +3
o 1
m -5; m -5; m -4
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +4
o 1
m +5; m +4
o 1
m +5; m +1
o 1
m -5; m -5; m -5
o 1
m +5; m +5; m +3
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -2
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +3
o 1
m +5
o 1
m -2
o 1
m +2
o 1
m +5; m +5; m +1
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5
o 1
m +5; m +5; m +2
o 1
m -3
o 1
m -2
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -2
o 1
m +5; m +5; m +5; m +2
o 1
m -5; m -5; m -5; m -2
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +4
o 1
m -5
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -4
o 1
m +5; m +5; m +5; m +5; m +5
o 1
m -5; m -5; m -5; m -5; m -5
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +4
o 1
m -5
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5
o 1
m -4
o 1
m -5; m -5; m -1
o 1
m +2
o 1
m +2
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +4
o 1
m -5; m -5
o 1
m +5; m +1
o 1
m -3
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -2
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +3
o 1
m +5; m +1
o 1
m -5; m -5; m -2
o 1
m -5; m -5; m -1
o 1
m +5; m +5; m +3
o 1
m -3
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -1
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +3
o 1
m +5
o 1
m +5; m +1
o 1
m -5
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +4
o 1
m -5; m -5; m -2
o 1
m -3
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5
o 1
m +2
o 2
m +5; m +5; m +2
o 1
m +3
o 1
m -5; m -5; m -4
o 1
m +5
o 1
m +5
o 1
m -5; m -2
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -1
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +3
o 1
m -3
o 1
m -5; m -5; m -5
o 1
m +2
o 1
m +2
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -1
o 2
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +4
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -3
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +3
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5
o 5; o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +2
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +2
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -1
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +1
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5
o 5; o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +4
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -3
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +3
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -2
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +5; m +5
m +5; m +5; m +5; m +2
o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -5; m -5; m -5
m -5; m -5; m -4
o 1
m +5; m +5; m +5; m +5; m +5
m +5; m +5
o 5; o 1
m -5; m -5; m -5; m -5; m -5
m -5; m -5
o 1
l:
	m -1
:l
r 5; r 5; r 5
m +1
l 2
l:
	m -1
	l 5; l 5; l 5
	m +1
	l 1
	m +1
	r 5; r 5; r 5; r 1
:l
l 5; l 5; l 5; l 1
l:
	m -1
	r 5; r 5; r 5; r 1
	m +1
	l 5; l 5; l 5; l 1
:l
r 2
m +1
l 1
l:

	l:
		m -1
	:l
	r 1
	m -1
	l 1
:l
r 5; r 5; r 5; r 1
l:
	m -1
	l 5; l 5; l 5; l 2
	m +1
	l 1
	m +1
	r 5; r 5; r 5; r 3
:l
l 5; l 5; l 5; l 3
l:
	m -1
	r 5; r 5; r 5; r 3
	m +1
	l 5; l 5; l 5; l 3
:l
r 2
m +1
l 1
l:

	l:
		m -1
	:l
	r 1
	m -1
	l 1
:l
l 1
l:
	m -1
:l
r 3
l:
	m -1
	l 3
	m +1
	l 2
	m +1
	r 5
:l
l 5
l:
	m -1
	r 5
	m +1
	l 5
:l
r 1
l:
	m -1
:l
r 3
l:
	m -1
	l 3
	m +1
	l 1
	m +1
	r 4
:l
l 4
l:
	m -1
	r 4
	m +1
	l 4
:l
r 2
l:
	m -1
	l 1
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
:l
l 1
l:
	m -1
:l
r 5
l:
	m -1
:l
l 3
l:
	m -1
	r 3
	m +1
	l 3
:l

l:
	m -1
:l
r 1
l:
	m -1
:l
r 1
l:
	m -1
:l
r 1
l:
	r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 3
	:l
	r 1
	m -1
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +3
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -4
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +1
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -3
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +4
		o 1
		m +1
		o 1
		m -3
		o 1
		m -4
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -2
		o 1
		m -5; m -5; m -5; m -5; m -3
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		l 1
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +4
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +1
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -3
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +4
		o 1
		m +1
		o 1
		m -3
		o 1
		m -4
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -2
		o 1
		m -5; m -5; m -5; m -5; m -3
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	i 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	m -1
	r 5; r 5; r 4
	l:
		m -1
	:l
	l 5; l 5; l 4
	l:
		m -1
		r 5; r 5; r 4
		m +1
		l 5; l 5; l 4
	:l
	r 5; r 5; r 5
	l:
		m -1
	:l
	l 5; l 5; l 5; l 2
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +2
	r 5; r 5; r 5; r 1
	l:
		m -1
		l 5; l 5; l 5; l 3
		m +1
		l 4
		m +1
		r 5; r 5; r 5; r 5; r 2
	:l
	l 5; l 5; l 5; l 5; l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 2
		m +1
		l 5; l 5; l 5; l 5; l 2
	:l
	r 5; r 1
	l:
		m -1
		l 3
		m +1
		l 3
		m +1
		r 5; r 1
	:l
	l 5; l 1
	l:
		m -1
		r 5; r 1
		m +1
		l 5; l 1
	:l
	r 4
	l:
		l 2
		m +1
		r 1
		l:
			m -1
			l 1
			l:
				m -1
			:l
			l 1
			m +1
			r 2
		:l
		l 1
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 2
		m -1
		r 1
		m -1
	:l
	l 1
	l:
		m -1
	:l
	r 4
	l:
		m -1
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		m -1
	:l
	l 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +1
	r 5; r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 4
		m +1
		r 5; r 5; r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 3
	:l
	r 5; r 1
	l:
		m -1
		l 3
		m +1
		l 3
		m +1
		r 5; r 1
	:l
	l 5; l 1
	l:
		m -1
		r 5; r 1
		m +1
		l 5; l 1
	:l
	r 4
	l:
		l 2
		m +1
		r 1
		l:
			m -1
			l 1
			l:
				m -1
			:l
			l 1
			m +1
			r 2
		:l
		l 1
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 2
		m -1
		r 1
		m -1
	:l
	l 1
	l:
		m -1
	:l
	r 4
	l:
		m -1
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:

		l:
			m -1
		:l
		l 1
		m -1
		r 1
	:l
	l 1
	l:
		m -1
		r 1
		m +1
		l 1
	:l
	l 1
	l:
		m -1
	:l
	r 4
	l:
		m -1
		l 4
		m +1
		l 2
		m +1
		r 5; r 1
	:l
	l 5; l 1
	l:
		m -1
		r 5; r 1
		m +1
		l 5; l 1
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
			l 5; l 5; l 5; l 5; l 1
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 5; r 2
		:l
		l 5; l 5; l 5; l 5; l 2
		l:
			m -1
			r 5; r 5; r 5; r 5; r 2
			m +1
			l 5; l 5; l 5; l 5; l 2
		:l
		r 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -3
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 2
			m +1
			r 5; r 5; r 4
		:l
		l 5; l 5; l 4
		l:
			m -1
			r 5; r 5; r 4
			m +1
			l 5; l 5; l 4
		:l
		r 5; r 5; r 2
		l:
			m -1
			l 1
			m +1
			l 5; l 5; l 1
			m +1
			r 5; r 5; r 2
		:l
		l 5; l 5; l 2
		l:
			m -1
			r 5; r 5; r 2
			m +1
			l 5; l 5; l 2
		:l
		r 5; r 5; r 5; r 5; r 5
		l:
			m -1
			l 5; l 5; l 5; l 1
			m +1
			l 5; l 4
			m +1
			r 5; r 5; r 5; r 5; r 5
		:l
		l 5; l 5; l 5; l 5; l 5
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			m +1
			l 5; l 5; l 5; l 5; l 5
		:l
		r 5; r 5; r 5; r 5; r 5
		r 1
		l:
			m -1
			l 5; l 5; l 5; l 3
			m +1
			l 5; l 3
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 1
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 1
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 1
		:l
		r 5; r 5; r 5; r 5; r 5
		r 2
		l:
			m -1
			l 5; l 5; l 5; l 5
			m +1
			l 5; l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 2
		:l
		l 5; l 5; l 5; l 5; l 5
		l 2
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 2
		:l
		r 5; r 5; r 5; r 5; r 5
		r 3
		l:
			m -1
			l 5; l 5; l 5; l 5; l 2
			m +1
			l 5; l 1
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 3
		:l
		l 5; l 5; l 5; l 5; l 5
		l 3
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 3
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 3
		:l
		r 5; r 5; r 5; r 5; r 5
		r 4
		l:
			m -1
			l 5; l 5; l 5; l 5; l 4
			m +1
			l 5
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 4
		:l
		r 5; r 5; r 5; r 5; r 5
		r 5
		l:
			m -1
			l 5; l 5; l 5; l 5; l 5
			l 1
			m +1
			l 4
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5
		:l
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
		l:
			m -1
			l 5; l 5; l 5; l 5; l 5
			l 3
			m +1
			l 3
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 1
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 1
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 1
		:l
		r 5; r 5; r 5; r 5; r 5
		r 5; r 2
		l:
			m -1
			l 5; l 5; l 5; l 5; l 5
			l 5
			m +1
			l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 2
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 2
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 2
		:l
		r 5; r 5; r 5; r 5; r 5
		r 5; r 3
		l:
			m -1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 2
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 3
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 3
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 3
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 3
		:l
		r 5; r 5; r 2
		l:
			l 3
			l:
				m -1
				r 4
				m +1
				l 4
			:l
			r 2
			l:
				m -1
				l 1
				m +1
				r 1
			:l
			r 1
			l:
				m -1
				l 1
				m +1
				r 1
			:l
			l 1
			m -1
		:l
		l 3
		l:
			m -1
			r 1
			m +1
			r 2
			m +1
			l 3
		:l
		r 3
		l:
			m -1
			l 3
			m +1
			r 3
		:l
		l 1
		l:

			l:
				m -1
				r 1
				m +1
				l 1
			:l
			l 1
			l:
				m -1
				r 1
				m +1
				l 1
			:l
			r 4
			l:
				m -1
				l 4
				m +1
				r 4
			:l
			l 2
			m -1
		:l
		l 1
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		r 5; r 5; r 2
		l:
			m -1
			l 2
			m +1
			l 1
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 2
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			r 5; r 5; r 5; r 5; r 4
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				l 1
				m +1
				l 1
				m +1
				r 5; r 5; r 5; r 5; r 5
				r 2
			:l
			l 5; l 5; l 5; l 5; l 5
			l 2
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				r 2
				m +1
				l 5; l 5; l 5; l 5; l 5
				l 2
			:l
			r 1
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -3
			l 2
			l:
				m -1
			:l
			r 2
			l:
				m -1
				l 2
				m +1
				l 5; l 5; l 2
				m +1
				r 5; r 5; r 4
			:l
			l 5; l 5; l 4
			l:
				m -1
				r 5; r 5; r 4
				m +1
				l 5; l 5; l 4
			:l
			r 5; r 5; r 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
				l 1
				m +1
				l 5; l 5; l 1
				m +1
				r 5; r 5; r 2
			:l
			l 5; l 5; l 2
			l:
				m -1
				r 5; r 5; r 2
				m +1
				l 5; l 5; l 2
			:l
			r 5; r 5
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 4
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 4
				m +1
				l 5; l 5
				m +1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 5; r 5; r 4
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 4
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 5; r 5; r 4
				m +1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 5; l 5; l 4
			:l
			r 5; r 4
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 1
			l:
				m -1
				l 5; l 5; l 5; l 5; l 1
				m +1
				r 5; r 5; r 5; r 5; r 1
			:l
			l 5; l 5; l 5; l 5; l 2
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 3
			l:
				m -1
				l 5; l 5; l 5; l 5; l 3
				m +1
				r 5; r 5; r 5; r 5; r 3
			:l
			l 5; l 5; l 5; l 5; l 4
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 5
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				m +1
				r 5; r 5; r 5; r 5; r 5
			:l
			l 5; l 5; l 5; l 5; l 5
			l 1
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 5
			r 2
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				l 2
				m +1
				r 5; r 5; r 5; r 5; r 5
				r 2
			:l
			l 5; l 5; l 5; l 5; l 5
			l 3
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 5
			r 4
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				l 4
				m +1
				r 5; r 5; r 5; r 5; r 5
				r 4
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 1
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 1
				m +1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 1
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5; l 2
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 3
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 3
				m +1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 3
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5; l 4
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 5
				m +1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 5
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 1
			l:
				m -1
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 2
			l:
				m -1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 5; l 2
				m +1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 5; r 2
			:l
			l 5; l 5; l 5; l 5; l 5
			l 1
			l:
				l 3
				l:
					m -1
					r 4
					m +1
					l 4
				:l
				r 1
				l:
					m -1
					l 1
					m +1
					r 1
				:l
				r 1
				l:
					m -1
					l 1
					m +1
					r 1
				:l
				r 1
				l:
					m -1
					l 1
					m +1
					r 1
				:l
				l 1
				m -1
			:l
			l 3
			l:
				m -1
			:l
			r 1
			l:
				m -1
				l 1
				m +1
				r 1
			:l
			r 1
			l:

				l:
					m -1
					r 1
					m +1
					l 1
				:l
				r 3
				l:
					m -1
					l 4
					m +1
					r 4
				:l
				l 2
				m -1
			:l
			r 5; r 5; r 5; r 4
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 1
			l:
				m -1
				r 5; r 5; r 5; r 5; r 1
				m +1
				l 5; l 5; l 5; l 5; l 1
			:l
			r 5; r 5; r 5; r 5; r 2
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 3
			l:
				m -1
				r 5; r 5; r 5; r 5; r 3
				m +1
				l 5; l 5; l 5; l 5; l 3
			:l
			r 5; r 5; r 5; r 5; r 4
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 5
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				m +1
				l 5; l 5; l 5; l 5; l 5
			:l
			r 5; r 5; r 5; r 5; r 5
			r 1
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 5
			l 2
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				r 2
				m +1
				l 5; l 5; l 5; l 5; l 5
				l 2
			:l
			r 5; r 5; r 5; r 5; r 5
			r 3
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 5
			l 4
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				r 4
				m +1
				l 5; l 5; l 5; l 5; l 5
				l 4
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5; l 1
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 1
				m +1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 1
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 2
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5; l 3
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 3
				m +1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 3
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 4
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 5
				m +1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 5
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 1
			l:
				m -1
			:l
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 2
			l:
				m -1
				r 5; r 5; r 5; r 5; r 5
				r 5; r 5; r 2
				m +1
				l 5; l 5; l 5; l 5; l 5
				l 5; l 5; l 2
			:l
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5
			l:
				m -1
			:l
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 2
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5
			o 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +4
			o 1
			m +5; m +5; m +5; m +5
			o 1
			m -5; m -2
			o 1
			m +5; m +5; m +5; m +4
			o 1
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -5
			m -5; m -4
			o 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +3
			o 1
			m -2
			o 1
			m +4
			o 1
			m -5; m -5; m -5; m -5
			o 1
			m +5; m +5; m +5; m +2
			o 1
			m -5; m -5; m -3
			o 1
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -4
			o 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +3
			o 1
			m +5; m +5
			o 1
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -5
			m -5; m -3
			o 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5
			o 1
			m +5; m +5; m +1
			o 1
			m +5; m +1
			o 1
			m -5; m -5; m -3
			o 1
			m -4
			o 1
			m +3
			o 1
			m +5; m +5; m +5; m +5; m +1
			o 1
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -4
			o 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +4
			o 1
			m -5; m -5; m -5; m -4
			o 1
			m +5; m +5
			o 1
			m -5; m -1
			o 1
			m +5; m +4
			o 1
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -4
			o 1
			m -5; m -5; m -5; m -5; m -5
			m -5; m -5; m -1
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		l 1
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +3
		o 1
		m -5; m -2
		o 1
		m -4
		o 1
		m +5; m +5; m +5; m +3
		o 1
		m -5; m -5; m -4
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -4
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +4
		o 1
		m +5; m +4
		o 1
		m +5; m +1
		o 1
		m -5; m -5; m -5
		o 1
		m +5; m +5; m +3
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -2
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +3
		o 1
		m +5
		o 1
		m -2
		o 1
		m +2
		o 1
		m +5; m +5; m +1
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -4
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +1
		o 1
		m +3
		o 1
		m +5; m +5; m +5
		o 1
		m +3
		o 1
		m -5; m -5; m -5; m -3
		o 2
		m +5; m +4
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -3
		o 1
		m +5; m +5; m +5; m +2
		o 1
		m -5; m -5; m -5; m -2
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5
		o 1
		m +5; m +5; m +3
		o 1
		m -5; m -5
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -3
		o 1
		m +5; m +5; m +5; m +5; m +5
		o 1
		m -5; m -5; m -1
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -1
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 5; r 4
	l:
		m -1
	:l
	l 5; l 5; l 5; l 3
	m +5; m +5
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5
	l:
		m -1
		l 5; l 5; l 1
		m +1
		l 1
		m +1
		r 5; r 5; r 2
	:l
	l 5; l 5; l 2
	l:
		m -1
		r 5; r 5; r 2
		m +1
		l 5; l 5; l 2
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 2
		l:
			m -1
			l 5; l 5; l 4
			m +1
			l 1
			m +1
			r 5; r 5; r 5
		:l
		l 5; l 5; l 5
		l:
			m -1
			r 5; r 5; r 5
			m +1
			l 5; l 5; l 5
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 1
	l:
		m -1
		l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 3
	:l
	l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 3
		m +1
		l 5; l 5; l 3
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 3
		l:
			m -1
			l 5; l 5; l 5
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 1
		:l
		l 5; l 5; l 5; l 1
		l:
			m -1
			r 5; r 5; r 5; r 1
			m +1
			l 5; l 5; l 5; l 1
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 3
		m +1
		l 1
		m +1
		r 5; r 5; r 4
	:l
	l 5; l 5; l 4
	l:
		m -1
		r 5; r 5; r 4
		m +1
		l 5; l 5; l 4
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 4
		l:
			m -1
			l 5; l 5; l 5; l 1
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 2
		:l
		l 5; l 5; l 5; l 2
		l:
			m -1
			r 5; r 5; r 5; r 2
			m +1
			l 5; l 5; l 5; l 2
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5
	:l
	l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5
		m +1
		l 5; l 5; l 5
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 5
		l:
			m -1
			l 5; l 5; l 5; l 2
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 3
		:l
		l 5; l 5; l 5; l 3
		l:
			m -1
			r 5; r 5; r 5; r 3
			m +1
			l 5; l 5; l 5; l 3
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 1
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 5; r 1
		l:
			m -1
			l 5; l 5; l 5; l 3
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 4
		:l
		l 5; l 5; l 5; l 4
		l:
			m -1
			r 5; r 5; r 5; r 4
			m +1
			l 5; l 5; l 5; l 4
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 1
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 2
	:l
	l 5; l 5; l 5; l 2
	l:
		m -1
		r 5; r 5; r 5; r 2
		m +1
		l 5; l 5; l 5; l 2
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 5; r 2
		l:
			m -1
			l 5; l 5; l 5; l 4
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 5
		:l
		l 5; l 5; l 5; l 5
		l:
			m -1
			r 5; r 5; r 5; r 5
			m +1
			l 5; l 5; l 5; l 5
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 5; r 1
	l:
		m -1
		l 5; l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 3
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 5; r 3
		l:
			m -1
			l 5; l 5; l 5; l 5
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 5; r 1
		:l
		l 5; l 5; l 5; l 5; l 1
		l:
			m -1
			r 5; r 5; r 5; r 5; r 1
			m +1
			l 5; l 5; l 5; l 5; l 1
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 3
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 4
	:l
	l 5; l 5; l 5; l 4
	l:
		m -1
		r 5; r 5; r 5; r 4
		m +1
		l 5; l 5; l 5; l 4
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
			l 5; l 5; l 5; l 5; l 1
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 5; r 2
		:l
		l 5; l 5; l 5; l 5; l 2
		l:
			m -1
			r 5; r 5; r 5; r 5; r 2
			m +1
			l 5; l 5; l 5; l 5; l 2
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 4
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5
		o 5; o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 5; r 5; r 5; r 5
		l:
			m -1
			l 5; l 5; l 5; l 5; l 2
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 5; r 3
		:l
		l 5; l 5; l 5; l 5; l 3
		l:
			m -1
			r 5; r 5; r 5; r 5; r 3
			m +1
			l 5; l 5; l 5; l 5; l 3
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +5; m +5; m +5
			m +5; m +5; m +3
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +5; m +5; m +5; m +5; m +5
			m +5; m +2
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +4
	o 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5
	m +1
	l 5; l 5; l 5; l 4
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	m +5; m +5
	o 1
	l:
		m -1
	:l

	l:
		m -1
	:l
	r 5; r 4
	l:
		m -1
		l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 1
	:l
	l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 1
		m +1
		l 5; l 5; l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 1
	l:
		m -1
		l 5; l 5; l 1
		m +1
		l 2
		m +1
		r 5; r 5; r 3
	:l
	l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 3
		m +1
		l 5; l 5; l 3
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 2
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 4
	:l
	l 5; l 5; l 5; l 4
	l:
		m -1
		r 5; r 5; r 5; r 4
		m +1
		l 5; l 5; l 5; l 4
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 2
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 4
	:l
	l 5; l 5; l 5; l 5; l 4
	l:
		m -1
		r 5; r 5; r 5; r 5; r 4
		m +1
		l 5; l 5; l 5; l 5; l 4
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 2
	:l
	l 5; l 5; l 5; l 5; l 5
	l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 2
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 2
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 2
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 4
	:l
	l 5; l 5; l 5; l 5; l 5
	l 4
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 4
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 4
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 2
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 2
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 2
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 3
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 3
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 3
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 3
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 2
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 2
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 2
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 1
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 1
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 2
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 2
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 2
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 2
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 2
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 2
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 2
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 2
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 2
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 5; l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 5; r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 5; r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 5; l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 1
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 1
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 3
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 4
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 3
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 3
		m +1
		l 2
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 2
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 4
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 4
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 4
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 4
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 2
	l:
		m -1
	:l
	m +1
	l 5; l 5; l 3
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 1
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 1
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 2
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 2
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 2
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 1
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 3
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 3
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 4
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 4
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 4
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 4
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 3
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 4
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 4
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 1
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 1
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 2
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 2
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 2
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 2
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5; r 1
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 3
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 3
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 3
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5; r 2
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 3
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 4
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 4
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 4
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 4
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 3
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5; r 5; r 5; r 5
	r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 5; l 5; l 5
	l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 1
	:l
	r 1
	l:
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 5; r 5; r 5
		r 5; r 5; r 3
		l:
			m -1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5
			m +1
			l 1
			m +1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 1
		:l
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 5; l 5
		l 5; l 5; l 5; l 1
		l:
			m -1
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 1
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 1
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5
			l:
				m -1
			:l
			m +2
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 5; r 5
			r 5; r 5; r 5; r 1
			l:
				m -1
			:l
			m +1
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 5; l 5
			l 5; l 5; l 5; l 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 5; r 5; r 4
	l:
		m -1
		l 5; l 5; l 5
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 1
	:l
	l 5; l 5; l 5; l 1
	l:
		m -1
		r 5; r 5; r 5; r 1
		m +1
		l 5; l 5; l 5; l 1
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 5; r 5; r 5; r 1
	l:
		m -1
		l 5; l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 3
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 5
	l:
		m -1
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l

	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
:l
r 5; r 5; r 3
l:
	m -1
	l 5; l 5; l 4
	m +1
	l 1
	m +1
	r 5; r 5; r 5
:l
l 5; l 5; l 5
l:
	m -1
	r 5; r 5; r 5
	m +1
	l 5; l 5; l 5
:l
r 1
m -1
r 1
m +1
l 1
l:

	l:
		m -1
	:l
	r 1
	m -1
	l 1
:l
r 1
l:
	m -1
	l 1
	m +1
	l 2
	m +1
	r 3
:l
l 3
l:
	m -1
	r 3
	m +1
	l 3
:l
r 1
m +1
r 1
l:
	l 2
	m +5; m +5
	o 2
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +3
	o 1
	m -5; m -5; m -5; m -5; m -5
	m -5; m -5; m -5; m -5; m -5
	m -5; m -1
	o 1
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +5; m +5; m +5
	m +5; m +5; m +2
	o 1
	m -5; m -5; m -4
	o 1
	m +5
	o 1
	m +5
	o 1
	m -5; m -5; m -5; m -5; m -5
	m -5; m -5; m -5; m -5; m -5
	m -5; m -5; m -5; m -5; m -5
	m -5; m -2
	o 1
	l:
		m -1
	:l
	r 1
	m -1
	r 1
	l:
		m -1
	:l

:l
l 1
l:
	r 5; r 5; r 5
	l:
		m -1
		l 5; l 5; l 5; l 2
		m +1
		l 1
		m +1
		r 5; r 5; r 5; r 3
	:l
	l 5; l 5; l 5; l 3
	l:
		m -1
		r 5; r 5; r 5; r 3
		m +1
		l 5; l 5; l 5; l 3
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +5; m +5
		o 2
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +4
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -2
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +2
		o 1
		m -5; m -5; m -4
		o 1
		m +5
		o 1
		m +5
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -2
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		l 1
		m +5; m +5
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +5
		m +5; m +2
		o 1
		m +5; m +5; m +5; m +3
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -2
		o 1
		m +5; m +5; m +5; m +5; m +5
		m +5; m +5; m +5; m +5; m +1
		o 1
		m -5; m -5; m -5; m -2
		o 1
		m +5; m +5; m +5; m +5; m +2
		o 1
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -5; m -5; m -5
		m -5; m -5; m -1
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 2
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l

:l
