#!/usr/bin/env bs

# Name      : tictactoe
# Author    : unknown
# Purpose   : Tic Tac Toe game

l 1
m +10
o 1
m +25
m +25
m +24
o 1
m +21
o 1
m -6
o 1
m -15
o 1
m +13
o 1
m +2
o 1
m -15
o 1
m +25
m +2
o 1
m -10
o 1
m -25
m -25
m -25
m -16
o 2
m +25
m +25
m +20
o 1
m +25
m +3
o 1
m -7
o 1
m -4
o 1
m +18
o 1
m -14
o 1
m -25
m -25
m -19
o 1
m +25
m +25
m +19
o 1
m +9
o 1
m +6
o 1
m -15
o 1
m +13
o 1
m -25
m -25
m -25
m -7
o 1
m +25
m +25
m +15
o 1
m -25
m -25
m -15
o 1
m +25
m +25
m +18
o 1
m +5
o 1
m -2
o 1
m +2
o 1
m +11
o 1
m -25
m -25
m -25
m -9
o 1
m +25
m +25
m +20
o 1
m +12
o 1
m -3
o 1
m -2
o 1
m -25
m -25
m -25
m -2
o 1
m +17
o 1
m -17
o 1
m +25
m +25
m +25
m +9
o 1
m -5
o 1
m -25
m -25
m -25
m -4
o 1
m +25
o 1
m -25
o 1
m +25
m +25
m +25
m +9
o 1
m -5
o 1
m -25
m -25
m -25
m -4
o 1
m +25
m +25
m +25
m +5
o 1
m -4
o 1
m -11
o 1
m +2
o 1
m +2
o 1
m -25
m -25
m -19
o 1
m +25
m +25
m +25
m +14
o 1
m -10
o 1
m +6
o 1
m -3
o 1
m -25
m -25
m -25
m -7
o 1
m +25
m +25
m +25
m +8
o 1
m +6
o 1
m -12
o 1
m -11
o 1
m +13
o 1
m -3
o 1
m -25
m -25
m -25
m -1
o 1
m +25
m +25
m +23
o 1
m +5
o 1
m +6
o 1
m -5
o 1
m -25
m -25
m -25
m -4
o 1
m +25
m +25
m +25
m +9
o 1
m -12
o 1
m -3
o 1
m -25
m -25
m -19
o 1
m +25
m +25
m +15
o 1
m +2
o 2
m +12
o 1
m +3
o 1
m -14
o 1
m +5
o 1
m +5
o 1
m -7
o 1
m -25
m -25
m -21
o 1
m +25
m +25
m +25
m +8
o 1
m -3
o 1
m -15
o 1
m +2
o 1
m +2
o 1
m -25
m -25
m -25
m -16
o 2
m +25
m +14
o 1
m +25
m +25
m +25
o 1
m -25
m -25
m -24
o 1
m +25
m +25
m +24
o 1
m -25
m -25
m -23
o 1
m +25
m +25
m +23
o 1
m -25
m -25
m -25
m -25
m -14
o 1
m +25
m +10
o 6
m -25
m -10
o 1
m +25
m +17
o 1
m +25
m +25
m +22
o 1
m -25
m -25
m -21
o 1
m +25
m +25
m +21
o 1
m -25
m -25
m -20
o 1
m +25
m +25
m +20
o 1
m -25
m -25
m -25
m -25
m -14
o 1
m +25
m +10
o 6
m -25
m -10
o 1
m +25
m +20
o 1
m +25
m +25
m +19
o 1
m -25
m -25
m -18
o 1
m +25
m +25
m +18
o 1
m -25
m -25
m -17
o 1
m +25
m +25
m +17
o 1
m -25
m -25
m -25
m -25
m -14
o 1
m +25
m +10
o 6
m -25
m -10
o 1
l:
	m -1
:l
r 15
m +1
l 2
l:
	m -1
	l 15
	m +1
	l 1
	m +1
	r 16
:l
l 16
l:
	m -1
	r 16
	m +1
	l 16
:l
r 2
m +1
l 1
l:

	l:
		m -1
	:l
	r 1
	m -1
	l 1
:l
r 16
l:
	m -1
	l 17
	m +1
	l 1
	m +1
	r 18
:l
l 18
l:
	m -1
	r 18
	m +1
	l 18
:l
r 2
m +1
l 1
l:

	l:
		m -1
	:l
	r 1
	m -1
	l 1
:l
l 1
l:
	m -1
:l
r 3
l:
	m -1
	l 3
	m +1
	l 2
	m +1
	r 5
:l
l 5
l:
	m -1
	r 5
	m +1
	l 5
:l
r 1
l:
	m -1
:l
r 3
l:
	m -1
	l 3
	m +1
	l 1
	m +1
	r 4
:l
l 4
l:
	m -1
	r 4
	m +1
	l 4
:l
r 2
l:
	m -1
	l 1
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
:l
l 1
l:
	m -1
:l
r 5
l:
	m -1
:l
l 3
l:
	m -1
	r 3
	m +1
	l 3
:l

l:
	m -1
:l
r 1
l:
	m -1
:l
r 1
l:
	m -1
:l
r 1
l:
	r 15
	l:
		m -1
		l 17
		m +1
		l 1
		m +1
		r 18
	:l
	l 18
	l:
		m -1
		r 18
		m +1
		l 18
	:l
	r 1
	m -1
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +10
		o 1
		m +25
		m +25
		m +25
		m +3
		o 1
		m -25
		m -24
		o 1
		m +25
		m +25
		m +25
		m +1
		o 1
		m -25
		m -25
		m -25
		m -8
		o 1
		m +25
		m +25
		m +25
		m +9
		o 1
		m +1
		o 1
		m -3
		o 1
		m -4
		o 1
		m -25
		m -25
		m -25
		m -2
		o 1
		m -23
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		l 1
		m +10
		o 1
		m +25
		m +25
		m +19
		o 1
		m -25
		m -15
		o 1
		m +25
		m +25
		m +25
		m +1
		o 1
		m -25
		m -25
		m -25
		m -8
		o 1
		m +25
		m +25
		m +25
		m +9
		o 1
		m +1
		o 1
		m -3
		o 1
		m -4
		o 1
		m -25
		m -25
		m -25
		m -2
		o 1
		m -23
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	i 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	m -1
	r 14
	l:
		m -1
	:l
	l 14
	l:
		m -1
		r 14
		m +1
		l 14
	:l
	r 15
	l:
		m -1
	:l
	l 17
	m +25
	m +22
	r 16
	l:
		m -1
		l 18
		m +1
		l 4
		m +1
		r 22
	:l
	l 22
	l:
		m -1
		r 22
		m +1
		l 22
	:l
	r 6
	l:
		m -1
		l 3
		m +1
		l 3
		m +1
		r 6
	:l
	l 6
	l:
		m -1
		r 6
		m +1
		l 6
	:l
	r 4
	l:
		l 2
		m +1
		r 1
		l:
			m -1
			l 1
			l:
				m -1
			:l
			l 1
			m +1
			r 2
		:l
		l 1
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 2
		m -1
		r 1
		m -1
	:l
	l 1
	l:
		m -1
	:l
	r 4
	l:
		m -1
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		m -1
	:l
	l 1
	m +25
	m +25
	m +6
	r 17
	l:
		m -1
		l 19
		m +1
		l 4
		m +1
		r 23
	:l
	l 23
	l:
		m -1
		r 23
		m +1
		l 23
	:l
	r 6
	l:
		m -1
		l 3
		m +1
		l 3
		m +1
		r 6
	:l
	l 6
	l:
		m -1
		r 6
		m +1
		l 6
	:l
	r 4
	l:
		l 2
		m +1
		r 1
		l:
			m -1
			l 1
			l:
				m -1
			:l
			l 1
			m +1
			r 2
		:l
		l 1
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 2
		m -1
		r 1
		m -1
	:l
	l 1
	l:
		m -1
	:l
	r 4
	l:
		m -1
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:

		l:
			m -1
		:l
		l 1
		m -1
		r 1
	:l
	l 1
	l:
		m -1
		r 1
		m +1
		l 1
	:l
	l 1
	l:
		m -1
	:l
	r 4
	l:
		m -1
		l 4
		m +1
		l 2
		m +1
		r 6
	:l
	l 6
	l:
		m -1
		r 6
		m +1
		l 6
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		r 19
		l:
			m -1
			l 21
			m +1
			l 1
			m +1
			r 22
		:l
		l 22
		l:
			m -1
			r 22
			m +1
			l 22
		:l
		r 1
		m -25
		m -23
		l:
			m -1
			l 2
			m +1
			l 12
			m +1
			r 14
		:l
		l 14
		l:
			m -1
			r 14
			m +1
			l 14
		:l
		r 12
		l:
			m -1
			l 1
			m +1
			l 11
			m +1
			r 12
		:l
		l 12
		l:
			m -1
			r 12
			m +1
			l 12
		:l
		r 25
		l:
			m -1
			l 16
			m +1
			l 9
			m +1
			r 25
		:l
		l 25
		l:
			m -1
			r 25
			m +1
			l 25
		:l
		r 25
		r 1
		l:
			m -1
			l 18
			m +1
			l 8
			m +1
			r 25
			r 1
		:l
		l 25
		l 1
		l:
			m -1
			r 25
			r 1
			m +1
			l 25
			l 1
		:l
		r 25
		r 2
		l:
			m -1
			l 20
			m +1
			l 7
			m +1
			r 25
			r 2
		:l
		l 25
		l 2
		l:
			m -1
			r 25
			r 2
			m +1
			l 25
			l 2
		:l
		r 25
		r 3
		l:
			m -1
			l 22
			m +1
			l 6
			m +1
			r 25
			r 3
		:l
		l 25
		l 3
		l:
			m -1
			r 25
			r 3
			m +1
			l 25
			l 3
		:l
		r 25
		r 4
		l:
			m -1
			l 24
			m +1
			l 5
			m +1
			r 25
			r 4
		:l
		l 25
		l 4
		l:
			m -1
			r 25
			r 4
			m +1
			l 25
			l 4
		:l
		r 25
		r 5
		l:
			m -1
			l 25
			l 1
			m +1
			l 4
			m +1
			r 25
			r 5
		:l
		l 25
		l 5
		l:
			m -1
			r 25
			r 5
			m +1
			l 25
			l 5
		:l
		r 25
		r 6
		l:
			m -1
			l 25
			l 3
			m +1
			l 3
			m +1
			r 25
			r 6
		:l
		l 25
		l 6
		l:
			m -1
			r 25
			r 6
			m +1
			l 25
			l 6
		:l
		r 25
		r 7
		l:
			m -1
			l 25
			l 5
			m +1
			l 2
			m +1
			r 25
			r 7
		:l
		l 25
		l 7
		l:
			m -1
			r 25
			r 7
			m +1
			l 25
			l 7
		:l
		r 25
		r 8
		l:
			m -1
			l 25
			l 7
			m +1
			l 1
			m +1
			r 25
			r 8
		:l
		l 25
		l 8
		l:
			m -1
			r 25
			r 8
			m +1
			l 25
			l 8
		:l
		r 12
		l:
			l 3
			l:
				m -1
				r 4
				m +1
				l 4
			:l
			r 2
			l:
				m -1
				l 1
				m +1
				r 1
			:l
			r 1
			l:
				m -1
				l 1
				m +1
				r 1
			:l
			l 1
			m -1
		:l
		l 3
		l:
			m -1
			r 1
			m +1
			r 2
			m +1
			l 3
		:l
		r 3
		l:
			m -1
			l 3
			m +1
			r 3
		:l
		l 1
		l:

			l:
				m -1
				r 1
				m +1
				l 1
			:l
			l 1
			l:
				m -1
				r 1
				m +1
				l 1
			:l
			r 4
			l:
				m -1
				l 4
				m +1
				r 4
			:l
			l 2
			m -1
		:l
		l 1
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		l 1
		l:
			m -1
		:l
		r 12
		l:
			m -1
			l 2
			m +1
			l 1
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 2
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			r 24
			l:
				m -1
				l 25
				l 1
				m +1
				l 1
				m +1
				r 25
				r 2
			:l
			l 25
			l 2
			l:
				m -1
				r 25
				r 2
				m +1
				l 25
				l 2
			:l
			r 1
			m -25
			m -23
			l 2
			l:
				m -1
			:l
			r 2
			l:
				m -1
				l 2
				m +1
				l 12
				m +1
				r 14
			:l
			l 14
			l:
				m -1
				r 14
				m +1
				l 14
			:l
			r 11
			l:
				m -1
			:l
			r 1
			l:
				m -1
				l 1
				m +1
				l 11
				m +1
				r 12
			:l
			l 12
			l:
				m -1
				r 12
				m +1
				l 12
			:l
			r 10
			l:
				m -1
			:l
			r 25
			r 9
			l:
				m -1
				l 25
				l 9
				m +1
				l 10
				m +1
				r 25
				r 19
			:l
			l 25
			l 19
			l:
				m -1
				r 25
				r 19
				m +1
				l 25
				l 19
			:l
			r 9
			l:
				m -1
			:l
			r 21
			l:
				m -1
				l 21
				m +1
				r 21
			:l
			l 22
			l:
				m -1
			:l
			r 23
			l:
				m -1
				l 23
				m +1
				r 23
			:l
			l 24
			l:
				m -1
			:l
			r 25
			l:
				m -1
				l 25
				m +1
				r 25
			:l
			l 25
			l 1
			l:
				m -1
			:l
			r 25
			r 2
			l:
				m -1
				l 25
				l 2
				m +1
				r 25
				r 2
			:l
			l 25
			l 3
			l:
				m -1
			:l
			r 25
			r 4
			l:
				m -1
				l 25
				l 4
				m +1
				r 25
				r 4
			:l
			l 25
			l 5
			l:
				m -1
			:l
			r 25
			r 6
			l:
				m -1
				l 25
				l 6
				m +1
				r 25
				r 6
			:l
			l 25
			l 7
			l:
				m -1
			:l
			r 25
			r 8
			l:
				m -1
				l 25
				l 8
				m +1
				r 25
				r 8
			:l
			l 25
			l 9
			l:
				m -1
			:l
			r 25
			r 10
			l:
				m -1
				l 25
				l 10
				m +1
				r 25
				r 10
			:l
			l 25
			l 11
			l:
				m -1
			:l
			r 25
			r 12
			l:
				m -1
				l 25
				l 12
				m +1
				r 25
				r 12
			:l
			l 25
			l 1
			l:
				l 3
				l:
					m -1
					r 4
					m +1
					l 4
				:l
				r 1
				l:
					m -1
					l 1
					m +1
					r 1
				:l
				r 1
				l:
					m -1
					l 1
					m +1
					r 1
				:l
				r 1
				l:
					m -1
					l 1
					m +1
					r 1
				:l
				l 1
				m -1
			:l
			l 3
			l:
				m -1
			:l
			r 1
			l:
				m -1
				l 1
				m +1
				r 1
			:l
			r 1
			l:

				l:
					m -1
					r 1
					m +1
					l 1
				:l
				r 3
				l:
					m -1
					l 4
					m +1
					r 4
				:l
				l 2
				m -1
			:l
			r 19
			l:
				m -1
			:l
			l 21
			l:
				m -1
				r 21
				m +1
				l 21
			:l
			r 22
			l:
				m -1
			:l
			l 23
			l:
				m -1
				r 23
				m +1
				l 23
			:l
			r 24
			l:
				m -1
			:l
			l 25
			l:
				m -1
				r 25
				m +1
				l 25
			:l
			r 25
			r 1
			l:
				m -1
			:l
			l 25
			l 2
			l:
				m -1
				r 25
				r 2
				m +1
				l 25
				l 2
			:l
			r 25
			r 3
			l:
				m -1
			:l
			l 25
			l 4
			l:
				m -1
				r 25
				r 4
				m +1
				l 25
				l 4
			:l
			r 25
			r 5
			l:
				m -1
			:l
			l 25
			l 6
			l:
				m -1
				r 25
				r 6
				m +1
				l 25
				l 6
			:l
			r 25
			r 7
			l:
				m -1
			:l
			l 25
			l 8
			l:
				m -1
				r 25
				r 8
				m +1
				l 25
				l 8
			:l
			r 25
			r 9
			l:
				m -1
			:l
			l 25
			l 10
			l:
				m -1
				r 25
				r 10
				m +1
				l 25
				l 10
			:l
			r 25
			r 11
			l:
				m -1
			:l
			l 25
			l 12
			l:
				m -1
				r 25
				r 12
				m +1
				l 25
				l 12
			:l
			r 25
			r 15
			l:
				m -1
			:l
			m +1
			l 25
			l 2
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +10
			o 1
			m +25
			m +25
			m +24
			o 1
			m +20
			o 1
			m -7
			o 1
			m +19
			o 1
			m -25
			m -25
			m -25
			m -9
			o 1
			m +25
			m +25
			m +25
			m +8
			o 1
			m -2
			o 1
			m +4
			o 1
			m -20
			o 1
			m +17
			o 1
			m -13
			o 1
			m -25
			m -25
			m -19
			o 1
			m +25
			m +25
			m +23
			o 1
			m +10
			o 1
			m -25
			m -25
			m -25
			m -8
			o 1
			m +25
			m +25
			m +15
			o 1
			m +11
			o 1
			m +6
			o 1
			m -13
			o 1
			m -4
			o 1
			m +3
			o 1
			m +21
			o 1
			m -25
			m -25
			m -25
			m -14
			o 1
			m +25
			m +25
			m +25
			m +9
			o 1
			m -19
			o 1
			m +10
			o 1
			m -6
			o 1
			m +9
			o 1
			m -25
			m -25
			m -14
			o 1
			m -25
			m -11
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		l 1
		m +10
		o 1
		m +25
		m +25
		m +20
		o 1
		m +25
		m +3
		o 1
		m -7
		o 1
		m -4
		o 1
		m +18
		o 1
		m -14
		o 1
		m -25
		m -25
		m -19
		o 1
		m +25
		m +25
		m +19
		o 1
		m +9
		o 1
		m +6
		o 1
		m -15
		o 1
		m +13
		o 1
		m -25
		m -25
		m -25
		m -7
		o 1
		m +25
		m +25
		m +15
		o 1
		m -25
		m -25
		m -15
		o 1
		m +25
		m +25
		m +18
		o 1
		m +5
		o 1
		m -2
		o 1
		m +2
		o 1
		m +11
		o 1
		m -25
		m -25
		m -25
		m -9
		o 1
		m +25
		m +25
		m +16
		o 1
		m +3
		o 1
		m +15
		o 1
		m +3
		o 1
		m -18
		o 2
		m +9
		o 1
		m -25
		m -25
		m -25
		m -3
		o 1
		m +17
		o 1
		m -17
		o 1
		m +25
		m +25
		m +15
		o 1
		m +13
		o 1
		m -10
		o 1
		m -25
		m -25
		m -18
		o 1
		m +25
		o 1
		m -11
		o 1
		m -25
		m -11
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 19
	l:
		m -1
	:l
	l 18
	m +10
	o 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 10
	l:
		m -1
		l 11
		m +1
		l 1
		m +1
		r 12
	:l
	l 12
	l:
		m -1
		r 12
		m +1
		l 12
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 12
		l:
			m -1
			l 14
			m +1
			l 1
			m +1
			r 15
		:l
		l 15
		l:
			m -1
			r 15
			m +1
			l 15
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 11
	l:
		m -1
		l 12
		m +1
		l 1
		m +1
		r 13
	:l
	l 13
	l:
		m -1
		r 13
		m +1
		l 13
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 13
		l:
			m -1
			l 15
			m +1
			l 1
			m +1
			r 16
		:l
		l 16
		l:
			m -1
			r 16
			m +1
			l 16
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 12
	l:
		m -1
		l 13
		m +1
		l 1
		m +1
		r 14
	:l
	l 14
	l:
		m -1
		r 14
		m +1
		l 14
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 14
		l:
			m -1
			l 16
			m +1
			l 1
			m +1
			r 17
		:l
		l 17
		l:
			m -1
			r 17
			m +1
			l 17
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 13
	l:
		m -1
		l 14
		m +1
		l 1
		m +1
		r 15
	:l
	l 15
	l:
		m -1
		r 15
		m +1
		l 15
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 15
		l:
			m -1
			l 17
			m +1
			l 1
			m +1
			r 18
		:l
		l 18
		l:
			m -1
			r 18
			m +1
			l 18
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 14
	l:
		m -1
		l 15
		m +1
		l 1
		m +1
		r 16
	:l
	l 16
	l:
		m -1
		r 16
		m +1
		l 16
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 16
		l:
			m -1
			l 18
			m +1
			l 1
			m +1
			r 19
		:l
		l 19
		l:
			m -1
			r 19
			m +1
			l 19
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 15
	l:
		m -1
		l 16
		m +1
		l 1
		m +1
		r 17
	:l
	l 17
	l:
		m -1
		r 17
		m +1
		l 17
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 17
		l:
			m -1
			l 19
			m +1
			l 1
			m +1
			r 20
		:l
		l 20
		l:
			m -1
			r 20
			m +1
			l 20
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 16
	l:
		m -1
		l 17
		m +1
		l 1
		m +1
		r 18
	:l
	l 18
	l:
		m -1
		r 18
		m +1
		l 18
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 18
		l:
			m -1
			l 20
			m +1
			l 1
			m +1
			r 21
		:l
		l 21
		l:
			m -1
			r 21
			m +1
			l 21
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 17
	l:
		m -1
		l 18
		m +1
		l 1
		m +1
		r 19
	:l
	l 19
	l:
		m -1
		r 19
		m +1
		l 19
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 19
		l:
			m -1
			l 21
			m +1
			l 1
			m +1
			r 22
		:l
		l 22
		l:
			m -1
			r 22
			m +1
			l 22
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -3
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 19
		l:
			m -1
		:l
		l 20
		m +10
		o 1
		m +25
		m +10
		o 6
		m -25
		m -10
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 18
	l:
		m -1
		l 19
		m +1
		l 1
		m +1
		r 20
	:l
	l 20
	l:
		m -1
		r 20
		m +1
		l 20
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +25
		m +25
		m +25
		m +4
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		r 20
		l:
			m -1
			l 22
			m +1
			l 1
			m +1
			r 23
		:l
		l 23
		l:
			m -1
			r 23
			m +1
			l 23
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			l 2
			m +25
			m +25
			m +25
			m +13
			o 1
			l:
				m -1
			:l
			r 1
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			l 1
			m +25
			m +7
			o 1
			l:
				m -1
			:l
			r 1
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	m +25
	m +25
	m +25
	m +25
	m +24
	o 1
	l:
		m -1
	:l
	r 20
	m +1
	l 19
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	m +10
	o 1
	l:
		m -1
	:l

	l:
		m -1
	:l
	r 9
	l:
		m -1
		l 9
		m +1
		l 2
		m +1
		r 11
	:l
	l 11
	l:
		m -1
		r 11
		m +1
		l 11
	:l
	r 1
	l:
		m -1
	:l
	r 24
	l:
		m -1
		l 24
		m +1
		l 1
		m +1
		r 25
	:l
	l 25
	l:
		m -1
		r 25
		m +1
		l 25
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 11
	l:
		m -1
		l 11
		m +1
		l 2
		m +1
		r 13
	:l
	l 13
	l:
		m -1
		r 13
		m +1
		l 13
	:l
	r 1
	l:
		m -1
	:l
	r 25
	l:
		m -1
		l 25
		m +1
		l 1
		m +1
		r 25
		r 1
	:l
	l 25
	l 1
	l:
		m -1
		r 25
		r 1
		m +1
		l 25
		l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 14
	l:
		m -1
		l 14
		m +1
		l 2
		m +1
		r 16
	:l
	l 16
	l:
		m -1
		r 16
		m +1
		l 16
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 2
	l:
		m -1
		l 25
		l 2
		m +1
		l 1
		m +1
		r 25
		r 3
	:l
	l 25
	l 3
	l:
		m -1
		r 25
		r 3
		m +1
		l 25
		l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 25
			l 2
			m +1
			r 25
			r 4
		:l
		l 25
		l 4
		l:
			m -1
			r 25
			r 4
			m +1
			l 25
			l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 17
	l:
		m -1
		l 17
		m +1
		l 2
		m +1
		r 19
	:l
	l 19
	l:
		m -1
		r 19
		m +1
		l 19
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 4
	l:
		m -1
		l 25
		l 4
		m +1
		l 1
		m +1
		r 25
		r 5
	:l
	l 25
	l 5
	l:
		m -1
		r 25
		r 5
		m +1
		l 25
		l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 19
	l:
		m -1
		l 19
		m +1
		l 2
		m +1
		r 21
	:l
	l 21
	l:
		m -1
		r 21
		m +1
		l 21
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 5
	l:
		m -1
		l 25
		l 5
		m +1
		l 1
		m +1
		r 25
		r 6
	:l
	l 25
	l 6
	l:
		m -1
		r 25
		r 6
		m +1
		l 25
		l 6
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 22
	l:
		m -1
		l 22
		m +1
		l 2
		m +1
		r 24
	:l
	l 24
	l:
		m -1
		r 24
		m +1
		l 24
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 7
	l:
		m -1
		l 25
		l 7
		m +1
		l 1
		m +1
		r 25
		r 8
	:l
	l 25
	l 8
	l:
		m -1
		r 25
		r 8
		m +1
		l 25
		l 8
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 6
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 25
			l 7
			m +1
			r 25
			r 9
		:l
		l 25
		l 9
		l:
			m -1
			r 25
			r 9
			m +1
			l 25
			l 9
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	l:
		m -1
		l 25
		m +1
		l 2
		m +1
		r 25
		r 2
	:l
	l 25
	l 2
	l:
		m -1
		r 25
		r 2
		m +1
		l 25
		l 2
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 9
	l:
		m -1
		l 25
		l 9
		m +1
		l 1
		m +1
		r 25
		r 10
	:l
	l 25
	l 10
	l:
		m -1
		r 25
		r 10
		m +1
		l 25
		l 10
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 2
	l:
		m -1
		l 25
		l 2
		m +1
		l 2
		m +1
		r 25
		r 4
	:l
	l 25
	l 4
	l:
		m -1
		r 25
		r 4
		m +1
		l 25
		l 4
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 10
	l:
		m -1
		l 25
		l 10
		m +1
		l 1
		m +1
		r 25
		r 11
	:l
	l 25
	l 11
	l:
		m -1
		r 25
		r 11
		m +1
		l 25
		l 11
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 5
	l:
		m -1
		l 25
		l 5
		m +1
		l 2
		m +1
		r 25
		r 7
	:l
	l 25
	l 7
	l:
		m -1
		r 25
		r 7
		m +1
		l 25
		l 7
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 12
	l:
		m -1
		l 25
		l 12
		m +1
		l 1
		m +1
		r 25
		r 13
	:l
	l 25
	l 13
	l:
		m -1
		r 25
		r 13
		m +1
		l 25
		l 13
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 11
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 25
			l 12
			m +1
			r 25
			r 14
		:l
		l 25
		l 14
		l:
			m -1
			r 25
			r 14
			m +1
			l 25
			l 14
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 24
	l:
		m -1
		l 24
		m +1
		l 2
		m +1
		r 25
		r 1
	:l
	l 25
	l 1
	l:
		m -1
		r 25
		r 1
		m +1
		l 25
		l 1
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 14
	l:
		m -1
		l 25
		l 14
		m +1
		l 1
		m +1
		r 25
		r 15
	:l
	l 25
	l 15
	l:
		m -1
		r 25
		r 15
		m +1
		l 25
		l 15
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 3
	l:
		m -1
		l 25
		l 3
		m +1
		l 2
		m +1
		r 25
		r 5
	:l
	l 25
	l 5
	l:
		m -1
		r 25
		r 5
		m +1
		l 25
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 15
	l:
		m -1
		l 25
		l 15
		m +1
		l 1
		m +1
		r 25
		r 16
	:l
	l 25
	l 16
	l:
		m -1
		r 25
		r 16
		m +1
		l 25
		l 16
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 8
	l:
		m -1
		l 25
		l 8
		m +1
		l 2
		m +1
		r 25
		r 10
	:l
	l 25
	l 10
	l:
		m -1
		r 25
		r 10
		m +1
		l 25
		l 10
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 17
	l:
		m -1
		l 25
		l 17
		m +1
		l 1
		m +1
		r 25
		r 18
	:l
	l 25
	l 18
	l:
		m -1
		r 25
		r 18
		m +1
		l 25
		l 18
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 16
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 25
			l 17
			m +1
			r 25
			r 19
		:l
		l 25
		l 19
		l:
			m -1
			r 25
			r 19
			m +1
			l 25
			l 19
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 5
	l:
		m -1
		l 25
		l 5
		m +1
		l 2
		m +1
		r 25
		r 7
	:l
	l 25
	l 7
	l:
		m -1
		r 25
		r 7
		m +1
		l 25
		l 7
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 19
	l:
		m -1
		l 25
		l 19
		m +1
		l 1
		m +1
		r 25
		r 20
	:l
	l 25
	l 20
	l:
		m -1
		r 25
		r 20
		m +1
		l 25
		l 20
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 9
	l:
		m -1
		l 25
		l 9
		m +1
		l 2
		m +1
		r 25
		r 11
	:l
	l 25
	l 11
	l:
		m -1
		r 25
		r 11
		m +1
		l 25
		l 11
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 20
	l:
		m -1
		l 25
		l 20
		m +1
		l 1
		m +1
		r 25
		r 21
	:l
	l 25
	l 21
	l:
		m -1
		r 25
		r 21
		m +1
		l 25
		l 21
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 14
	l:
		m -1
		l 25
		l 14
		m +1
		l 2
		m +1
		r 25
		r 16
	:l
	l 25
	l 16
	l:
		m -1
		r 25
		r 16
		m +1
		l 25
		l 16
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 22
	l:
		m -1
		l 25
		l 22
		m +1
		l 1
		m +1
		r 25
		r 23
	:l
	l 25
	l 23
	l:
		m -1
		r 25
		r 23
		m +1
		l 25
		l 23
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 21
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 25
			l 22
			m +1
			r 25
			r 24
		:l
		l 25
		l 24
		l:
			m -1
			r 25
			r 24
			m +1
			l 25
			l 24
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 11
	l:
		m -1
		l 25
		l 11
		m +1
		l 2
		m +1
		r 25
		r 13
	:l
	l 25
	l 13
	l:
		m -1
		r 25
		r 13
		m +1
		l 25
		l 13
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 24
	l:
		m -1
		l 25
		l 24
		m +1
		l 1
		m +1
		r 25
		r 25
	:l
	l 25
	l 25
	l:
		m -1
		r 25
		r 25
		m +1
		l 25
		l 25
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 15
	l:
		m -1
		l 25
		l 15
		m +1
		l 2
		m +1
		r 25
		r 17
	:l
	l 25
	l 17
	l:
		m -1
		r 25
		r 17
		m +1
		l 25
		l 17
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	l:
		m -1
		l 25
		l 25
		m +1
		l 1
		m +1
		r 25
		r 25
		r 1
	:l
	l 25
	l 25
	l 1
	l:
		m -1
		r 25
		r 25
		r 1
		m +1
		l 25
		l 25
		l 1
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 20
	l:
		m -1
		l 25
		l 20
		m +1
		l 2
		m +1
		r 25
		r 22
	:l
	l 25
	l 22
	l:
		m -1
		r 25
		r 22
		m +1
		l 25
		l 22
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 2
	l:
		m -1
		l 25
		l 25
		l 2
		m +1
		l 1
		m +1
		r 25
		r 25
		r 3
	:l
	l 25
	l 25
	l 3
	l:
		m -1
		r 25
		r 25
		r 3
		m +1
		l 25
		l 25
		l 3
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 1
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 25
			l 25
			l 2
			m +1
			r 25
			r 25
			r 4
		:l
		l 25
		l 25
		l 4
		l:
			m -1
			r 25
			r 25
			r 4
			m +1
			l 25
			l 25
			l 4
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 14
	l:
		m -1
		l 25
		l 14
		m +1
		l 2
		m +1
		r 25
		r 16
	:l
	l 25
	l 16
	l:
		m -1
		r 25
		r 16
		m +1
		l 25
		l 16
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 4
	l:
		m -1
		l 25
		l 25
		l 4
		m +1
		l 1
		m +1
		r 25
		r 25
		r 5
	:l
	l 25
	l 25
	l 5
	l:
		m -1
		r 25
		r 25
		r 5
		m +1
		l 25
		l 25
		l 5
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 19
	l:
		m -1
		l 25
		l 19
		m +1
		l 2
		m +1
		r 25
		r 21
	:l
	l 25
	l 21
	l:
		m -1
		r 25
		r 21
		m +1
		l 25
		l 21
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 5
	l:
		m -1
		l 25
		l 25
		l 5
		m +1
		l 1
		m +1
		r 25
		r 25
		r 6
	:l
	l 25
	l 25
	l 6
	l:
		m -1
		r 25
		r 25
		r 6
		m +1
		l 25
		l 25
		l 6
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	l:
		m -1
		l 25
		l 25
		m +1
		l 2
		m +1
		r 25
		r 25
		r 2
	:l
	l 25
	l 25
	l 2
	l:
		m -1
		r 25
		r 25
		r 2
		m +1
		l 25
		l 25
		l 2
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 7
	l:
		m -1
		l 25
		l 25
		l 7
		m +1
		l 1
		m +1
		r 25
		r 25
		r 8
	:l
	l 25
	l 25
	l 8
	l:
		m -1
		r 25
		r 25
		r 8
		m +1
		l 25
		l 25
		l 8
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 6
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 25
			l 25
			l 7
			m +1
			r 25
			r 25
			r 9
		:l
		l 25
		l 25
		l 9
		l:
			m -1
			r 25
			r 25
			r 9
			m +1
			l 25
			l 25
			l 9
		:l
		r 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 21
	l:
		m -1
		l 25
		l 21
		m +1
		l 2
		m +1
		r 25
		r 23
	:l
	l 25
	l 23
	l:
		m -1
		r 25
		r 23
		m +1
		l 25
		l 23
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 9
	l:
		m -1
		l 25
		l 25
		l 9
		m +1
		l 1
		m +1
		r 25
		r 25
		r 10
	:l
	l 25
	l 25
	l 10
	l:
		m -1
		r 25
		r 25
		r 10
		m +1
		l 25
		l 25
		l 10
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l

	l:
		m -1
	:l
	r 25
	r 24
	l:
		m -1
		l 25
		l 24
		m +1
		l 2
		m +1
		r 25
		r 25
		r 1
	:l
	l 25
	l 25
	l 1
	l:
		m -1
		r 25
		r 25
		r 1
		m +1
		l 25
		l 25
		l 1
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 10
	l:
		m -1
		l 25
		l 25
		l 10
		m +1
		l 1
		m +1
		r 25
		r 25
		r 11
	:l
	l 25
	l 25
	l 11
	l:
		m -1
		r 25
		r 25
		r 11
		m +1
		l 25
		l 25
		l 11
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 3
	l:
		m -1
		l 25
		l 25
		l 3
		m +1
		l 2
		m +1
		r 25
		r 25
		r 5
	:l
	l 25
	l 25
	l 5
	l:
		m -1
		r 25
		r 25
		r 5
		m +1
		l 25
		l 25
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 12
	l:
		m -1
		l 25
		l 25
		l 12
		m +1
		l 1
		m +1
		r 25
		r 25
		r 13
	:l
	l 25
	l 25
	l 13
	l:
		m -1
		r 25
		r 25
		r 13
		m +1
		l 25
		l 25
		l 13
	:l
	r 2
	l:
		m -1
		l 1
		m -1
		r 1
	:l
	m +1
	l 1
	l:
		r 1
		m -1
		l 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 2
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 11
		l:
			m -1
		:l
		r 2
		l:
			m -1
			l 2
			m +1
			l 25
			l 25
			l 12
			m +1
			r 25
			r 25
			r 14
		:l
		l 25
		l 25
		l 14
		l:
			m -1
			r 25
			r 25
			r 14
			m +1
			l 25
			l 25
			l 14
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 25
	r 25
	r 12
	l:
		m -1
	:l
	m +1
	l 13
	l:
		m -1
		l 25
		l 25
		m +1
		l 1
		m +1
		r 25
		r 25
		r 1
	:l
	l 25
	l 25
	l 1
	l:
		m -1
		r 25
		r 25
		r 1
		m +1
		l 25
		l 25
		l 1
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	l:
		m -1
		l 25
		l 25
		l 1
		m +1
		l 1
		m +1
		r 25
		r 25
		r 2
	:l
	l 25
	l 25
	l 2
	l:
		m -1
		r 25
		r 25
		r 2
		m +1
		l 25
		l 25
		l 2
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 1
	l:
		m -1
		l 25
		l 25
		l 2
		m +1
		l 1
		m +1
		r 25
		r 25
		r 3
	:l
	l 25
	l 25
	l 3
	l:
		m -1
		r 25
		r 25
		r 3
		m +1
		l 25
		l 25
		l 3
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 2
	l:
		m -1
		l 25
		l 25
		l 3
		m +1
		l 1
		m +1
		r 25
		r 25
		r 4
	:l
	l 25
	l 25
	l 4
	l:
		m -1
		r 25
		r 25
		r 4
		m +1
		l 25
		l 25
		l 4
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 3
	l:
		m -1
		l 25
		l 25
		l 4
		m +1
		l 1
		m +1
		r 25
		r 25
		r 5
	:l
	l 25
	l 25
	l 5
	l:
		m -1
		r 25
		r 25
		r 5
		m +1
		l 25
		l 25
		l 5
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 4
	l:
		m -1
		l 25
		l 25
		l 5
		m +1
		l 1
		m +1
		r 25
		r 25
		r 6
	:l
	l 25
	l 25
	l 6
	l:
		m -1
		r 25
		r 25
		r 6
		m +1
		l 25
		l 25
		l 6
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 5
	l:
		m -1
		l 25
		l 25
		l 6
		m +1
		l 1
		m +1
		r 25
		r 25
		r 7
	:l
	l 25
	l 25
	l 7
	l:
		m -1
		r 25
		r 25
		r 7
		m +1
		l 25
		l 25
		l 7
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 6
	l:
		m -1
		l 25
		l 25
		l 7
		m +1
		l 1
		m +1
		r 25
		r 25
		r 8
	:l
	l 25
	l 25
	l 8
	l:
		m -1
		r 25
		r 25
		r 8
		m +1
		l 25
		l 25
		l 8
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 7
	l:
		m -1
		l 25
		l 25
		l 8
		m +1
		l 1
		m +1
		r 25
		r 25
		r 9
	:l
	l 25
	l 25
	l 9
	l:
		m -1
		r 25
		r 25
		r 9
		m +1
		l 25
		l 25
		l 9
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 1
		m +1
		r 2
	:l
	l 2
	l:
		m -1
		r 2
		m +1
		l 2
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
		:l
		l 25
		l 25
		l 13
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 25
	r 25
	r 10
	l:
		m -1
		l 25
		l 25
		l 10
		m +1
		l 1
		m +1
		r 25
		r 25
		r 11
	:l
	l 25
	l 25
	l 11
	l:
		m -1
		r 25
		r 25
		r 11
		m +1
		l 25
		l 25
		l 11
	:l
	r 1
	l:
		r 25
		r 25
		r 13
		l:
			m -1
			l 25
			l 25
			l 15
			m +1
			l 1
			m +1
			r 25
			r 25
			r 16
		:l
		l 25
		l 25
		l 16
		l:
			m -1
			r 25
			r 25
			r 16
			m +1
			l 25
			l 25
			l 16
		:l
		r 1
		m -1
		r 1
		m +1
		l 1
		l:

			l:
				m -1
			:l
			r 1
			m -1
			l 1
		:l
		r 1
		l:
			m -1
			l 1
			m +1
			l 2
			m +1
			r 3
		:l
		l 3
		l:
			m -1
			r 3
			m +1
			l 3
		:l
		r 1
		m +1
		r 1
		l:
			r 25
			r 25
			r 15
			l:
				m -1
			:l
			m +2
			l 25
			l 25
			l 16
			m -1
			r 1
			l:
				m -1
			:l

		:l
		l 1
		l:
			r 25
			r 25
			r 16
			l:
				m -1
			:l
			m +1
			l 25
			l 25
			l 16
			l:
				m -1
			:l

		:l
		r 2
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 14
	l:
		m -1
		l 15
		m +1
		l 1
		m +1
		r 16
	:l
	l 16
	l:
		m -1
		r 16
		m +1
		l 16
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 16
	l:
		m -1
		l 17
		m +1
		l 1
		m +1
		r 18
	:l
	l 18
	l:
		m -1
		r 18
		m +1
		l 18
	:l
	r 2
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	l 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 2
		m +1
		r 5
	:l
	l 5
	l:
		m -1
		r 5
		m +1
		l 5
	:l
	r 1
	l:
		m -1
	:l
	r 3
	l:
		m -1
		l 3
		m +1
		l 1
		m +1
		r 4
	:l
	l 4
	l:
		m -1
		r 4
		m +1
		l 4
	:l
	r 2
	l:
		m -1
		l 1
		l:
			m -1
			r 2
			m +1
			l 2
		:l
		r 1
	:l
	l 1
	l:
		m -1
	:l
	r 5
	l:
		m -1
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l

	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l
	r 1
:l
r 13
l:
	m -1
	l 14
	m +1
	l 1
	m +1
	r 15
:l
l 15
l:
	m -1
	r 15
	m +1
	l 15
:l
r 1
m -1
r 1
m +1
l 1
l:

	l:
		m -1
	:l
	r 1
	m -1
	l 1
:l
r 1
l:
	m -1
	l 1
	m +1
	l 2
	m +1
	r 3
:l
l 3
l:
	m -1
	r 3
	m +1
	l 3
:l
r 1
m +1
r 1
l:
	l 2
	m +10
	o 2
	m +25
	m +25
	m +25
	m +3
	o 1
	m -25
	m -25
	m -6
	o 1
	m +25
	m +25
	m +25
	m +12
	o 1
	m -14
	o 1
	m +5
	o 1
	m +5
	o 1
	m -25
	m -25
	m -25
	m -7
	o 1
	l:
		m -1
	:l
	r 1
	m -1
	r 1
	l:
		m -1
	:l

:l
l 1
l:
	r 15
	l:
		m -1
		l 17
		m +1
		l 1
		m +1
		r 18
	:l
	l 18
	l:
		m -1
		r 18
		m +1
		l 18
	:l
	r 1
	m -2
	r 1
	m +1
	l 1
	l:

		l:
			m -1
		:l
		r 1
		m -1
		l 1
	:l
	r 1
	l:
		m -1
		l 1
		m +1
		l 2
		m +1
		r 3
	:l
	l 3
	l:
		m -1
		r 3
		m +1
		l 3
	:l
	r 1
	m +1
	r 1
	l:
		l 2
		m +10
		o 2
		m +25
		m +25
		m +19
		o 1
		m -25
		m -22
		o 1
		m +25
		m +25
		m +25
		m +12
		o 1
		m -14
		o 1
		m +5
		o 1
		m +5
		o 1
		m -25
		m -25
		m -25
		m -7
		o 1
		l:
			m -1
		:l
		r 1
		m -1
		r 1
		l:
			m -1
		:l

	:l
	l 1
	l:
		l 1
		m +10
		o 1
		m +25
		m +25
		m +25
		m +7
		o 1
		m +18
		o 1
		m -25
		m -17
		o 1
		m +25
		m +21
		o 1
		m -17
		o 1
		m +22
		o 1
		m -25
		m -25
		m -25
		m -11
		o 1
		l:
			m -1
		:l
		r 1
		l:
			m -1
		:l

	:l
	r 2
	l:
		m -1
	:l
	r 1
	l:
		m -1
	:l

:l
